config/routes.rb
Rails.application.routes.draw do
  resources :builds

end

app/models/build.rb
class Build < ActiveRecord::Base
	mount_uploader :buildFilePath, BuildUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
  before_action :set_build, only: [:show, :edit, :update, :destroy]

  # GET /builds
  # GET /builds.json
  def index
    @builds = Build.all
  end

  # GET /builds/1
  # GET /builds/1.json
  def show
  end

  # GET /builds/new
  def new
    @build = Build.new
  end

  # GET /builds/1/edit
  def edit
  end

  # POST /builds
  # POST /builds.json
  def create
    @build = Build.new(build_params)

    respond_to do |format|
      if @build.save
        if(@build.buildFilePath.file.exists?)
          #Read ipa or apk here
          extension = File.extname(@build.buildFilePath.url)
          if (extension == ".ipa")
            format.html { redirect_to @build, notice: 'Build was successfully created. And IPA uploaded' }
            # puts @build.buildFilePath.url
            ipa = Lagunitas::IPA.new(Dir.pwd + '/public' + @build.buildFilePath.url)
            app = ipa.app     #=> Lagunitas::App

              # Get information about the app
            puts app.identifier    #=> com.samsoffes.Sample
            puts app.display_name  #=> Sample
            puts app.version       #=> 13
            puts app.short_version #=> 2.2
              # Remove unzipped app
            ipa.cleanup

            manifestObj = {'items' => 
                            [{ 'assets' => 
                              [{'kind' => 'software-package', 
                                'url' =>'https://192.168.1.62:3001' + @build.buildFilePath.url }],
                              'metadata' =>
                               {'bundle-identifier' =>  app.identifier,
                               'bundle-version' => app.short_version,
                               'kind' => 'software',
                               'title' => app.display_name}

                            #   ], {'bundle-identifier' =>  app.identifier, 
                            #     'bundle-version' => app.version,
                            #     'kind' => 'software',
                            #     'title' => app.display_name}
                            }]
                          }
            # puts @build.buildFilePath.
            str = @build.buildFilePath.url
            list = str.split('/')
            path = '/public' + list[0..list.count-2].join('/') + '/manifest.plist'
            puts path
            # pathList = @build.buildFilePath.url
            # directory = 
            File.open(Dir.pwd + path, 'w') {|f| f.write(Plist::Emit.dump(manifestObj)) }



          elsif (extension == ".apk")            
            format.html { redirect_to @build, notice: 'Build was successfully created. And APK uploaded' }
          else
            format.html { redirect_to @build, notice: 'Build was successfully created. And file uploaded' }
          end
        else
          format.html { redirect_to @build, notice: 'Build was successfully created. But no file is uploaded' }
        end
        format.json { render :show, status: :created, location: @build }
      else
        format.html { render :new }
        format.json { render json: @build.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /builds/1
  # PATCH/PUT /builds/1.json
  def update
    respond_to do |format|
      if @build.update(build_params)
        format.html { redirect_to @build, notice: 'Build was successfully updated.' }
        format.json { render :show, status: :ok, location: @build }
      else
        format.html { render :edit }
        format.json { render json: @build.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /builds/1
  # DELETE /builds/1.json
  def destroy
    @build.destroy
    respond_to do |format|
      format.html { redirect_to builds_url, notice: 'Build was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_build
      @build = Build.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def build_params
      params.require(:build).permit(:number, :version, :releaseNotes, :platform, :buildIdenifier, :accessToken, :domain, :provision, :displayname, :icon, :buildFilePath)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/builds_helper.rb
module BuildsHelper
end

app/views/builds/_form.html.erb
<%= form_for @build, :html => {:multipart => true} do |f| %>
  <% if @build.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@build.errors.count, "error") %> prohibited this build from being saved:</h2>

      <ul>
      <% @build.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!--   <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :version %><br>
    <%= f.text_field :version %>
  </div> -->
  <div class="field">
    <%= f.label :releaseNotes %><br>
    <%= f.text_area :releaseNotes %>
  </div>
  <div class="field">
<!--     <%= f.label :platform %><br>
    <%= f.text_field :platform %>
 -->  
  <%= f.radio_button :platform, "iPhone" %>
  <%= f.label 'iPhone' %><br>
  <%= f.radio_button :platform, "iPad" %>
  <%= f.label 'iPad' %><br>
  <%= f.radio_button :platform, "iOS Universal" %>
  <%= f.label 'iOS Universal' %><br>
  <%= f.radio_button :platform, "Android" %>
  <%= f.label 'Android' %><br>

  </div>
<!--   <div class="field">
    <%= f.label :buildIdenifier %><br>
    <%= f.text_field :buildIdenifier %>
  </div> -->
  <div class="field">
    <%= f.label :accessToken %><br>
    <%= f.text_field :accessToken %>
  </div>
  <div class="field">
    <%= f.label :domain %><br>
    <%= f.text_field :domain %>
  </div>
  <div class="field">
    <%= f.label :provision %><br>
    <%= f.text_field :provision %>
  </div>
  <div class="field">
    <%= f.label :displayname %><br>
    <%= f.text_field :displayname %>
  </div>
  <div class="field">
    <%= f.label :icon %><br>
    <!-- <%= f.text_field :icon %> -->
  </div>
  <div class="field">
    <%= f.label :buildFilePath %><br>
    <%= f.file_field :buildFilePath %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/builds/edit.html.erb
<h1>Editing build</h1>

<%= render 'form' %>

<%= link_to 'Show', @build %> |
<%= link_to 'Back', builds_path %>

app/views/builds/index.html.erb
<h1>Listing builds</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Version</th>
      <th>Releasenotes</th>
      <th>Platform</th>
      <th>Buildidenifier</th>
      <th>Accesstoken</th>
      <th>Domain</th>
      <th>Provision</th>
      <th>Displayname</th>
      <th>Icon</th>
      <th>Buildfilepath</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @builds.each do |build| %>
      <tr>
        <td><%= build.number %></td>
        <td><%= build.version %></td>
        <td><%= build.releaseNotes %></td>
        <td><%= build.platform %></td>
        <td><%= build.buildIdenifier %></td>
        <td><%= build.accessToken %></td>
        <td><%= build.domain %></td>
        <td><%= build.provision %></td>
        <td><%= build.displayname %></td>
        <td><%= build.icon %></td>
        <td><%= build.buildFilePath %></td>
        <td><%= link_to 'Show', build %></td>
        <td><%= link_to 'Edit', edit_build_path(build) %></td>
        <td><%= link_to 'Destroy', build, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Build', new_build_path %>

app/views/builds/new.html.erb
<h1>New build</h1>

<%= render 'form' %>

<%= link_to 'Back', builds_path %>

app/views/builds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @build.number %>
</p>

<p>
  <strong>Version:</strong>
  <%= @build.version %>
</p>

<p>
  <strong>Releasenotes:</strong>
  <%= @build.releaseNotes %>
</p>

<p>
  <strong>Platform:</strong>
  <%= @build.platform %>
</p>

<p>
  <strong>Buildidenifier:</strong>
  <%= @build.buildIdenifier %>
</p>

<p>
  <strong>Accesstoken:</strong>
  <%= @build.accessToken %>
</p>

<p>
  <strong>Domain:</strong>
  <%= @build.domain %>
</p>

<p>
  <strong>Provision:</strong>
  <%= @build.provision %>
</p>

<p>
  <strong>Displayname:</strong>
  <%= @build.displayname %>
</p>

<p>
  <strong>Icon:</strong>
  <%= @build.icon %>
</p>

<p>
  <strong>Buildfilepath:</strong>
  <%= @build.buildFilePath %>
</p>
<p>
  <strong>OTA:</strong>
  <%
        str = @build.buildFilePath.url
      list = str.split('/')
      path = list[0..list.count-2].join('/') + '/manifest.plist'
    %>
    <%=
   link_to 'Install OTA', 'itms-services://?action=download-manifest&url=https://192.168.1.62:3001'+path %>
</p>
<%= link_to 'Edit', edit_build_path(@build) %> |
<%= link_to 'Back', builds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stella</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>